[package]
name = "AntHiveRust"
version = "0.1.0"
authors = ["Kivenkantaja Kivenkantaja <bushuevdv@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
